name: jon
favicon: null
layout_spectrum: 0.113
typography_spectrum: 0.5384439146146178
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11728581064380705
  lightness: 0.19026680407114327
  saturation: 0.6873201881535351
  rhythmicContrast: 0.25
purpose: []
